// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoes/cmds/CmdConst.proto

package com.alan.proto;

public final class CmdConst {
  private CmdConst() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code protobuf.Cmd_ID}
   */
  public enum Cmd_ID
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DOBATTLE = 0;</code>
     */
    DOBATTLE(0, 0),
    /**
     * <code>CHAT = 1;</code>
     */
    CHAT(1, 1),
    ;

    /**
     * <code>DOBATTLE = 0;</code>
     */
    public static final int DOBATTLE_VALUE = 0;
    /**
     * <code>CHAT = 1;</code>
     */
    public static final int CHAT_VALUE = 1;


    public final int getNumber() { return value; }

    public static Cmd_ID valueOf(int value) {
      switch (value) {
        case 0: return DOBATTLE;
        case 1: return CHAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Cmd_ID>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Cmd_ID>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Cmd_ID>() {
            public Cmd_ID findValueByNumber(int number) {
              return Cmd_ID.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.alan.proto.CmdConst.getDescriptor().getEnumTypes().get(0);
    }

    private static final Cmd_ID[] VALUES = values();

    public static Cmd_ID valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Cmd_ID(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:protobuf.Cmd_ID)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033protoes/cmds/CmdConst.proto\022\010protobuf*" +
      " \n\006Cmd_ID\022\014\n\010DOBATTLE\020\000\022\010\n\004CHAT\020\001B\020\n\016com" +
      ".alan.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
