// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protoes/cmds/CmdTest.proto

package com.alan.proto;

public final class CmdTest {
  private CmdTest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface Cmd_Arena_BattleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.Cmd_Arena_Battle)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 opponentRank = 1;</code>
     */
    boolean hasOpponentRank();
    /**
     * <code>required int32 opponentRank = 1;</code>
     */
    int getOpponentRank();

    /**
     * <code>required int64 opponentUid = 2;</code>
     */
    boolean hasOpponentUid();
    /**
     * <code>required int64 opponentUid = 2;</code>
     */
    long getOpponentUid();

    /**
     * <code>required int32 myRank = 3;</code>
     */
    boolean hasMyRank();
    /**
     * <code>required int32 myRank = 3;</code>
     */
    int getMyRank();

    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    java.util.List<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion> 
        getLegionsList();
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion getLegions(int index);
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    int getLegionsCount();
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    java.util.List<? extends com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder> 
        getLegionsOrBuilderList();
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder getLegionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.Cmd_Arena_Battle}
   */
  public static final class Cmd_Arena_Battle extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:protobuf.Cmd_Arena_Battle)
      Cmd_Arena_BattleOrBuilder {
    // Use Cmd_Arena_Battle.newBuilder() to construct.
    private Cmd_Arena_Battle(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Cmd_Arena_Battle(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Cmd_Arena_Battle defaultInstance;
    public static Cmd_Arena_Battle getDefaultInstance() {
      return defaultInstance;
    }

    public Cmd_Arena_Battle getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Cmd_Arena_Battle(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              opponentRank_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              opponentUid_ = input.readInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              myRank_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                legions_ = new java.util.ArrayList<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion>();
                mutable_bitField0_ |= 0x00000008;
              }
              legions_.add(input.readMessage(com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          legions_ = java.util.Collections.unmodifiableList(legions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.alan.proto.CmdTest.Cmd_Arena_Battle.class, com.alan.proto.CmdTest.Cmd_Arena_Battle.Builder.class);
    }

    public static com.google.protobuf.Parser<Cmd_Arena_Battle> PARSER =
        new com.google.protobuf.AbstractParser<Cmd_Arena_Battle>() {
      public Cmd_Arena_Battle parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Cmd_Arena_Battle(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Cmd_Arena_Battle> getParserForType() {
      return PARSER;
    }

    public interface Msg_legionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.Cmd_Arena_Battle.Msg_legion)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int32 index = 1;</code>
       */
      boolean hasIndex();
      /**
       * <code>required int32 index = 1;</code>
       */
      int getIndex();

      /**
       * <code>required int64 heroId = 2;</code>
       */
      boolean hasHeroId();
      /**
       * <code>required int64 heroId = 2;</code>
       */
      long getHeroId();
    }
    /**
     * Protobuf type {@code protobuf.Cmd_Arena_Battle.Msg_legion}
     */
    public static final class Msg_legion extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:protobuf.Cmd_Arena_Battle.Msg_legion)
        Msg_legionOrBuilder {
      // Use Msg_legion.newBuilder() to construct.
      private Msg_legion(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Msg_legion(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Msg_legion defaultInstance;
      public static Msg_legion getDefaultInstance() {
        return defaultInstance;
      }

      public Msg_legion getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Msg_legion(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                index_ = input.readInt32();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                heroId_ = input.readInt64();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.class, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder.class);
      }

      public static com.google.protobuf.Parser<Msg_legion> PARSER =
          new com.google.protobuf.AbstractParser<Msg_legion>() {
        public Msg_legion parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Msg_legion(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Msg_legion> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int INDEX_FIELD_NUMBER = 1;
      private int index_;
      /**
       * <code>required int32 index = 1;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }

      public static final int HEROID_FIELD_NUMBER = 2;
      private long heroId_;
      /**
       * <code>required int64 heroId = 2;</code>
       */
      public boolean hasHeroId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 heroId = 2;</code>
       */
      public long getHeroId() {
        return heroId_;
      }

      private void initFields() {
        index_ = 0;
        heroId_ = 0L;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasIndex()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasHeroId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt32(1, index_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, heroId_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, index_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, heroId_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.Cmd_Arena_Battle.Msg_legion}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobuf.Cmd_Arena_Battle.Msg_legion)
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.class, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder.class);
        }

        // Construct using com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          index_ = 0;
          bitField0_ = (bitField0_ & ~0x00000001);
          heroId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_descriptor;
        }

        public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion getDefaultInstanceForType() {
          return com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.getDefaultInstance();
        }

        public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion build() {
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion buildPartial() {
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion result = new com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.index_ = index_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.heroId_ = heroId_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion) {
            return mergeFrom((com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion other) {
          if (other == com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.getDefaultInstance()) return this;
          if (other.hasIndex()) {
            setIndex(other.getIndex());
          }
          if (other.hasHeroId()) {
            setHeroId(other.getHeroId());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasIndex()) {
            
            return false;
          }
          if (!hasHeroId()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private int index_ ;
        /**
         * <code>required int32 index = 1;</code>
         */
        public boolean hasIndex() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int32 index = 1;</code>
         */
        public int getIndex() {
          return index_;
        }
        /**
         * <code>required int32 index = 1;</code>
         */
        public Builder setIndex(int value) {
          bitField0_ |= 0x00000001;
          index_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int32 index = 1;</code>
         */
        public Builder clearIndex() {
          bitField0_ = (bitField0_ & ~0x00000001);
          index_ = 0;
          onChanged();
          return this;
        }

        private long heroId_ ;
        /**
         * <code>required int64 heroId = 2;</code>
         */
        public boolean hasHeroId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 heroId = 2;</code>
         */
        public long getHeroId() {
          return heroId_;
        }
        /**
         * <code>required int64 heroId = 2;</code>
         */
        public Builder setHeroId(long value) {
          bitField0_ |= 0x00000002;
          heroId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 heroId = 2;</code>
         */
        public Builder clearHeroId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          heroId_ = 0L;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:protobuf.Cmd_Arena_Battle.Msg_legion)
      }

      static {
        defaultInstance = new Msg_legion(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:protobuf.Cmd_Arena_Battle.Msg_legion)
    }

    private int bitField0_;
    public static final int OPPONENTRANK_FIELD_NUMBER = 1;
    private int opponentRank_;
    /**
     * <code>required int32 opponentRank = 1;</code>
     */
    public boolean hasOpponentRank() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 opponentRank = 1;</code>
     */
    public int getOpponentRank() {
      return opponentRank_;
    }

    public static final int OPPONENTUID_FIELD_NUMBER = 2;
    private long opponentUid_;
    /**
     * <code>required int64 opponentUid = 2;</code>
     */
    public boolean hasOpponentUid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 opponentUid = 2;</code>
     */
    public long getOpponentUid() {
      return opponentUid_;
    }

    public static final int MYRANK_FIELD_NUMBER = 3;
    private int myRank_;
    /**
     * <code>required int32 myRank = 3;</code>
     */
    public boolean hasMyRank() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 myRank = 3;</code>
     */
    public int getMyRank() {
      return myRank_;
    }

    public static final int LEGIONS_FIELD_NUMBER = 4;
    private java.util.List<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion> legions_;
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    public java.util.List<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion> getLegionsList() {
      return legions_;
    }
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    public java.util.List<? extends com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder> 
        getLegionsOrBuilderList() {
      return legions_;
    }
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    public int getLegionsCount() {
      return legions_.size();
    }
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion getLegions(int index) {
      return legions_.get(index);
    }
    /**
     * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
     */
    public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder getLegionsOrBuilder(
        int index) {
      return legions_.get(index);
    }

    private void initFields() {
      opponentRank_ = 0;
      opponentUid_ = 0L;
      myRank_ = 0;
      legions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOpponentRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasOpponentUid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMyRank()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLegionsCount(); i++) {
        if (!getLegions(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, opponentRank_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, opponentUid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, myRank_);
      }
      for (int i = 0; i < legions_.size(); i++) {
        output.writeMessage(4, legions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, opponentRank_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, opponentUid_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, myRank_);
      }
      for (int i = 0; i < legions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, legions_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.alan.proto.CmdTest.Cmd_Arena_Battle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.alan.proto.CmdTest.Cmd_Arena_Battle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.Cmd_Arena_Battle}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.Cmd_Arena_Battle)
        com.alan.proto.CmdTest.Cmd_Arena_BattleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.alan.proto.CmdTest.Cmd_Arena_Battle.class, com.alan.proto.CmdTest.Cmd_Arena_Battle.Builder.class);
      }

      // Construct using com.alan.proto.CmdTest.Cmd_Arena_Battle.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLegionsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        opponentRank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        opponentUid_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        myRank_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (legionsBuilder_ == null) {
          legions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          legionsBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.alan.proto.CmdTest.internal_static_protobuf_Cmd_Arena_Battle_descriptor;
      }

      public com.alan.proto.CmdTest.Cmd_Arena_Battle getDefaultInstanceForType() {
        return com.alan.proto.CmdTest.Cmd_Arena_Battle.getDefaultInstance();
      }

      public com.alan.proto.CmdTest.Cmd_Arena_Battle build() {
        com.alan.proto.CmdTest.Cmd_Arena_Battle result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.alan.proto.CmdTest.Cmd_Arena_Battle buildPartial() {
        com.alan.proto.CmdTest.Cmd_Arena_Battle result = new com.alan.proto.CmdTest.Cmd_Arena_Battle(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opponentRank_ = opponentRank_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.opponentUid_ = opponentUid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.myRank_ = myRank_;
        if (legionsBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            legions_ = java.util.Collections.unmodifiableList(legions_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.legions_ = legions_;
        } else {
          result.legions_ = legionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.alan.proto.CmdTest.Cmd_Arena_Battle) {
          return mergeFrom((com.alan.proto.CmdTest.Cmd_Arena_Battle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.alan.proto.CmdTest.Cmd_Arena_Battle other) {
        if (other == com.alan.proto.CmdTest.Cmd_Arena_Battle.getDefaultInstance()) return this;
        if (other.hasOpponentRank()) {
          setOpponentRank(other.getOpponentRank());
        }
        if (other.hasOpponentUid()) {
          setOpponentUid(other.getOpponentUid());
        }
        if (other.hasMyRank()) {
          setMyRank(other.getMyRank());
        }
        if (legionsBuilder_ == null) {
          if (!other.legions_.isEmpty()) {
            if (legions_.isEmpty()) {
              legions_ = other.legions_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureLegionsIsMutable();
              legions_.addAll(other.legions_);
            }
            onChanged();
          }
        } else {
          if (!other.legions_.isEmpty()) {
            if (legionsBuilder_.isEmpty()) {
              legionsBuilder_.dispose();
              legionsBuilder_ = null;
              legions_ = other.legions_;
              bitField0_ = (bitField0_ & ~0x00000008);
              legionsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLegionsFieldBuilder() : null;
            } else {
              legionsBuilder_.addAllMessages(other.legions_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpponentRank()) {
          
          return false;
        }
        if (!hasOpponentUid()) {
          
          return false;
        }
        if (!hasMyRank()) {
          
          return false;
        }
        for (int i = 0; i < getLegionsCount(); i++) {
          if (!getLegions(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.alan.proto.CmdTest.Cmd_Arena_Battle parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.alan.proto.CmdTest.Cmd_Arena_Battle) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int opponentRank_ ;
      /**
       * <code>required int32 opponentRank = 1;</code>
       */
      public boolean hasOpponentRank() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 opponentRank = 1;</code>
       */
      public int getOpponentRank() {
        return opponentRank_;
      }
      /**
       * <code>required int32 opponentRank = 1;</code>
       */
      public Builder setOpponentRank(int value) {
        bitField0_ |= 0x00000001;
        opponentRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 opponentRank = 1;</code>
       */
      public Builder clearOpponentRank() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opponentRank_ = 0;
        onChanged();
        return this;
      }

      private long opponentUid_ ;
      /**
       * <code>required int64 opponentUid = 2;</code>
       */
      public boolean hasOpponentUid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 opponentUid = 2;</code>
       */
      public long getOpponentUid() {
        return opponentUid_;
      }
      /**
       * <code>required int64 opponentUid = 2;</code>
       */
      public Builder setOpponentUid(long value) {
        bitField0_ |= 0x00000002;
        opponentUid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 opponentUid = 2;</code>
       */
      public Builder clearOpponentUid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        opponentUid_ = 0L;
        onChanged();
        return this;
      }

      private int myRank_ ;
      /**
       * <code>required int32 myRank = 3;</code>
       */
      public boolean hasMyRank() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 myRank = 3;</code>
       */
      public int getMyRank() {
        return myRank_;
      }
      /**
       * <code>required int32 myRank = 3;</code>
       */
      public Builder setMyRank(int value) {
        bitField0_ |= 0x00000004;
        myRank_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 myRank = 3;</code>
       */
      public Builder clearMyRank() {
        bitField0_ = (bitField0_ & ~0x00000004);
        myRank_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion> legions_ =
        java.util.Collections.emptyList();
      private void ensureLegionsIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          legions_ = new java.util.ArrayList<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion>(legions_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder> legionsBuilder_;

      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public java.util.List<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion> getLegionsList() {
        if (legionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(legions_);
        } else {
          return legionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public int getLegionsCount() {
        if (legionsBuilder_ == null) {
          return legions_.size();
        } else {
          return legionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion getLegions(int index) {
        if (legionsBuilder_ == null) {
          return legions_.get(index);
        } else {
          return legionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder setLegions(
          int index, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion value) {
        if (legionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLegionsIsMutable();
          legions_.set(index, value);
          onChanged();
        } else {
          legionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder setLegions(
          int index, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder builderForValue) {
        if (legionsBuilder_ == null) {
          ensureLegionsIsMutable();
          legions_.set(index, builderForValue.build());
          onChanged();
        } else {
          legionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder addLegions(com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion value) {
        if (legionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLegionsIsMutable();
          legions_.add(value);
          onChanged();
        } else {
          legionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder addLegions(
          int index, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion value) {
        if (legionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLegionsIsMutable();
          legions_.add(index, value);
          onChanged();
        } else {
          legionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder addLegions(
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder builderForValue) {
        if (legionsBuilder_ == null) {
          ensureLegionsIsMutable();
          legions_.add(builderForValue.build());
          onChanged();
        } else {
          legionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder addLegions(
          int index, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder builderForValue) {
        if (legionsBuilder_ == null) {
          ensureLegionsIsMutable();
          legions_.add(index, builderForValue.build());
          onChanged();
        } else {
          legionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder addAllLegions(
          java.lang.Iterable<? extends com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion> values) {
        if (legionsBuilder_ == null) {
          ensureLegionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, legions_);
          onChanged();
        } else {
          legionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder clearLegions() {
        if (legionsBuilder_ == null) {
          legions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          legionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public Builder removeLegions(int index) {
        if (legionsBuilder_ == null) {
          ensureLegionsIsMutable();
          legions_.remove(index);
          onChanged();
        } else {
          legionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder getLegionsBuilder(
          int index) {
        return getLegionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder getLegionsOrBuilder(
          int index) {
        if (legionsBuilder_ == null) {
          return legions_.get(index);  } else {
          return legionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public java.util.List<? extends com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder> 
           getLegionsOrBuilderList() {
        if (legionsBuilder_ != null) {
          return legionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(legions_);
        }
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder addLegionsBuilder() {
        return getLegionsFieldBuilder().addBuilder(
            com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder addLegionsBuilder(
          int index) {
        return getLegionsFieldBuilder().addBuilder(
            index, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.Cmd_Arena_Battle.Msg_legion legions = 4;</code>
       */
      public java.util.List<com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder> 
           getLegionsBuilderList() {
        return getLegionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder> 
          getLegionsFieldBuilder() {
        if (legionsBuilder_ == null) {
          legionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legion.Builder, com.alan.proto.CmdTest.Cmd_Arena_Battle.Msg_legionOrBuilder>(
                  legions_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          legions_ = null;
        }
        return legionsBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:protobuf.Cmd_Arena_Battle)
    }

    static {
      defaultInstance = new Cmd_Arena_Battle(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:protobuf.Cmd_Arena_Battle)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Cmd_Arena_Battle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Cmd_Arena_Battle_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032protoes/cmds/CmdTest.proto\022\010protobuf\"\262" +
      "\001\n\020Cmd_Arena_Battle\022\024\n\014opponentRank\030\001 \002(" +
      "\005\022\023\n\013opponentUid\030\002 \002(\003\022\016\n\006myRank\030\003 \002(\005\0226" +
      "\n\007legions\030\004 \003(\0132%.protobuf.Cmd_Arena_Bat" +
      "tle.Msg_legion\032+\n\nMsg_legion\022\r\n\005index\030\001 " +
      "\002(\005\022\016\n\006heroId\030\002 \002(\003B\020\n\016com.alan.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_Cmd_Arena_Battle_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_Cmd_Arena_Battle_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_Cmd_Arena_Battle_descriptor,
        new java.lang.String[] { "OpponentRank", "OpponentUid", "MyRank", "Legions", });
    internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_descriptor =
      internal_static_protobuf_Cmd_Arena_Battle_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_protobuf_Cmd_Arena_Battle_Msg_legion_descriptor,
        new java.lang.String[] { "Index", "HeroId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
